version: 2.1

orbs:
  github-status: samsalisbury/github-status@0.0.1

commands:
  print_env:
    parameters:
      exit_code:
        type: integer
    steps:
      - github-status/pending:
          description: sleeping 30s
      - run:
          name: printing env and sleeping 30s
          command: |
            set -euxo pipefail
            hidesecrets() { grep -vE '(TOKEN|SECRET|PASS|AUTH)'; }
            env | grep CIRCLE | hidesecrets
            echo ==================
            env | grep -v CIRCLE | hidesecrets
            echo ==================
            whoami
            echo ==================
            sleep 30
            exit <<parameters.exit_code>>
      - github-status/report

executors:
  buildpack_deps:
    docker:
      - image: circleci/buildpack-deps:19.04-curl
  classic_machine:
    machine:
      image: circleci/classic:latest

jobs:
  print_env_success:
    executor: buildpack_deps
    steps:
      - print_env:
          exit_code: 0
  print_env_fail:
    executor: buildpack_deps
    steps:
      - print_env:
          exit_code: 1
  print_env_success_machine:
    executor: classic_machine
    steps:
      - print_env:
          exit_code: 0
  print_env_fail_machine:
    executor: classic_machine
    steps:
      - print_env:
          exit_code: 1

workflows:
  failing:
    jobs:
      - print_env_fail
      - print_env_fail_machine
  succeeding:
    jobs:
      - print_env_success
      - print_env_success_machine
